name: Push File to Another Repository

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  push_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: AmandaWetter/A000_REBUILD  # Replace with the source repository (owner/repo)
          ref: main  # Adjust the branch or tag name as needed
          token: ${{ secrets.SOURCE_REPO_TOKEN }}  # Provide a token with repo access for private repositories

      - name: Create File
        run: echo "Content of the file" > new_file.txt  # Create the file with desired content

      - name: Checkout Destination Repository
        uses: actions/checkout@v2
        with:
          repository: ch-sz-geo/A000_entrypage  # Replace with the destination repository (owner/repo)
          token: ${{ secrets.DESTINATION_REPO_TOKEN }}  # Provide a token with repo access for private repositories

      - name: Add and Commit File
        run: |
          git add new_file.txt
          git commit -m "Add new file"
      
      - name: Push Changes
        run: git push origin HEAD:main  # Adjust the branch name as needed
