name: Ili File Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # [pull_request_target]
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

    workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      pages: write
    
    steps:
      - uses: actions/checkout@v3
      - name: Echo-Test
        run: echo 'Workflow 2 ist gestartet'